colorscheme slate
syntax on
set compatible
set number
set virtualedit=block
set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set showmatch
set cursorline
set cursorcolumn
set ignorecase
set smartcase
set hlsearch
set noerrorbells
set laststatus=2
set guioptions+=a
set smartindent
set noswapfile
filetype on
filetype plugin on
filetype plugin indent on
if filereadable("/etc/vim/vimrc.local")
endif
